### ISSUE TITLE
Incorrect Development release separators

### ISSUE THREAD

**Issue by jolpica** [Carreau/pep440#5]
## What
The tool doesn't support omitting of the separator before the "dev" in a release. e.g. `0.0.1dev1` when it should.

## Example
Running the following gives an output that it is not canonical
```zsh
$ pep440 "1.2dev2"
Version is not canonical according to Pep 440
```

However this is explicitly listed as an allowed pep440
https://peps.python.org/pep-0440/#development-release-separators

**Comment by Carreau** [comment]
Hi, thanks for your remark and issue. 

I think you missed that the sub-section you link to is part of the "normalisation" section:

> In order to maintain better compatibility with existing versions there are a number of “alternative” syntaxes that MUST be taken into account when **parsing** versions. These syntaxes MUST be considered when parsing a version, however they should be **“normalized”** to the standard syntax defined above.

Emphasis mine. 


Therefore the behavior of the package is correct, using a dash or no separator is not a canonical.

Pep440 is legacy so we should likely check this in the new guide close to the end:

https://packaging.python.org/en/latest/specifications/version-specifiers/#appendix-parsing-version-strings-with-regular-expressions

There are different regular expressions depending on wether you check for canonical, or are trying to parse and extract version info.
